@startuml

master -> repository: Write new trees
master -> clusterstate: Publish state referencing new trees as pending
master -> repository: Do writes (via peers)
master -> clusterstate: Publish state referencing new trees as completed
master -> repository: Write new commit
master -> clusterstate: Publish state referencing new commit as pending
master -> repository: Overwrite HEAD
master -> clusterstate: Publish state referencing new commit as completed

@enduml